### PR TITLE
Add setup ContentLength for proxyRequest

### PR DESCRIPTION
**Pull request by xorand**
proxyRequest is missing ContentLength and in some cases this one breaks work with some services

### CODE REVIEW

**Review by SamJakob — APPROVED** [review]
LGTM

**Review by NBTX — APPROVED** [review]

**Comment by SamJakob** [comment]
@AndrewBastin Not sure I have permissions to?

**Comment by AndrewBastin** [comment]
Oops, that was a misclick.

@SamJakob, sorry about that, I have given @NBTX Admin perms for this project.

**Comment by SamJakob** [comment]
Okay thanks! :+1:

**Pull request merged**
